version: '3'
services:
    web:
        build: .
        volumes:
            - /var/www/html/vendor
            - .:/var/www/html
        ports:
            - 8000:8000
        restart: always
        depends_on:
            - db
    db:
        image: mysql:latest
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=app
            - MYSQL_USER=user
            - MYSQL_PASSWORD=pass
        volumes:
            - db_data:/var/lib/mysql
        restart: always
    tests:
        image: "lehrermarktplatz/php-dev-test:latest"
        command: [ "-s", "basic" ]
        environment:
            APP_HOST: "web"
            APP_PORT: "8000"
volumes:
    db_data:
